services:
  bigtable-emulator-dumper:
    container_name: bigtable-emulator-dumper
    build:
      context: .
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    ports:
      - 8765:8080
